
POST http://xhsdz.echaokj.cn/Vote/GetAdd HTTP/1.1
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
# Cookie: VoteId=4
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36

VoteID=%2C4&Ip=58.246.8.255

GET http://xhsdz.echaokj.cn/Vote/GetVoteCountList HTTP/1.1